Homework1
made-ml-in-prod-2021/robertspb pull request #2
Opened 2021-05-16 20:59 UTC by robertspb

Буду рад любым комментариям и замечаниям!

В Reviewers не дает выбрать более одного и не дает делать поиск по группам teachers/students.

2021-05-22 20:48 UTC, robertspb commented
> > В Reviewers не дает выбрать более одного и не дает делать поиск по группам teachers/students.
> 
> Это потому что вы сделали этот репозиторий приватным

Спасибо, поправил! Был в полной уверенности, что создавал его публичным.

2021-05-23 16:30 UTC, ol-ga-00 requested changes
-2) Назовите ветку homework1 (1 балл) -- 1
-1) положите код в папку ml_project 
0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла) -- 0
 
1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов) -- 2
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы) 
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) -- 0
 
2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) -- 2
 
3) использованы логгеры (2 балла) -- 2
 
4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов) -- 1
 > мало тестов; нет теста всего пайплайна
5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов) -- 0
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается) 
 
6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) -- 3
 
7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла) -- 3
 
8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) -- 1 
 > в кастомном трансформере используется sklearn трансформер StandardScaler; и не написаны тесты на него 
9) Обучите модель, запишите в readme как это предлагается (3 балла) -- 3
 
10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)  -- 3
 
11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы) -- 0
 
12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) -- 0
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы) -- 0
 
 Итого 21 * 0.65 = 13.64

2021-05-23 16:31 UTC, ol-ga-00 approved these changes
Ставлю 15.6 баллов

2021-05-23 18:24 UTC, robertspb commented
Принято, спасибо!
Hydra в том виде, в котором используется в проекте (для конфигурации) - недостаточно для получения баллов?

2021-05-27 13:17 UTC, ol-ga-00 commented
> Принято, спасибо!
> Hydra в том виде, в котором используется в проекте (для конфигурации) - недостаточно для получения баллов?

Проглядела, извините
Добавила баллы, отредактировав свои комментарии

2021-05-27 13:17 UTC, ol-ga-00 commented
Если вопросов больше нет, то можете мёржить этот pr

2021-05-27 13:44 UTC, robertspb commented
> Если вопросов больше нет, то можете мёржить этот pr

Спасибо!

2021-05-27 13:45 UTC, merged